// @ts-ignore Generated by the OpenNext build.
import handler from "./.open-next/worker.js";
export { CareerApplicationWorkflow } from "./src/workflow";

export default {
  async fetch(
    request: Request,
    env: CloudflareEnv,
    ctx: ExecutionContext,
  ): Promise<Response> {
    const expectedEmail = env.CAREER_STUDIO_ACCESS_EMAIL?.toLowerCase();
    const authenticatedEmail = request.headers
      .get("Cf-Access-Authenticated-User-Email")
      ?.toLowerCase();
    const hostname = new URL(request.url).hostname;
    const hostHeader = request.headers.get("Host")?.split(":")[0];
    const isLocal =
      env.CAREER_STUDIO_LOCAL_DEV === "true" ||
      [hostname, hostHeader].some(
        (host) => host === "localhost" || host === "127.0.0.1",
      );

    if (!isLocal) {
      if (!expectedEmail) {
        return new Response("Career Studio access is not configured.", {
          status: 503,
        });
      }
      const accessAssertion = request.headers.get("Cf-Access-Jwt-Assertion");
      if (!accessAssertion || authenticatedEmail !== expectedEmail) {
        return new Response("Forbidden", { status: 403 });
      }
    }

    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;
